version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - mvn package -Dmaven.test.skip
      - mv target/auction.jar auction.jar
artifacts:
  type: zip
  files:
    - auction.jar
    - .ebextensions/**/*
    - .platform/**/*
    - Procfile
    - fonts/**/*
#   discard-paths: yes

