<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat|Arial|Raleway"
      rel="stylesheet"
    />
    <title>Nyyu</title>
  </head>
  <body>
    <div
      style="
        width: 500px;
        height: auto;
        padding-left: 30px;
        font-family: 'Montserrat', Arial, Raleway;
        overflow: hidden;
        "
    >
    <div
    style="
    padding-top: 10px
    "
    >
        <svg width="51" height="42" viewBox="0 0 51 42" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M26.2941 0H34.2692V5.98511H36.2642V7.98014H40.2543V5.98511H42.2494V0H50.2295V7.97514H48.2345V9.97018H46.2394V11.9652H42.2494V19.9454H34.2692V11.9652H30.2791V9.97018H28.2841V7.97514H26.2891V0H26.2941Z" fill="#63AAEB"/>
<path d="M0.00500116 22.041H7.98014V28.0261H9.97518V30.0212H13.9653V28.0261H15.9603V22.041H23.9404V30.0162H21.9454V32.0112H19.9504V34.0062H15.9603V41.9864H7.98014V34.0062H3.99007V32.0112H1.99504V30.0162H0V22.041H0.00500116Z" fill="#63AAEB"/>
<path d="M48.3535 42H28.2919V40.005H26.2969V22.0547H34.272V38.01H42.3684V22.0547H50.3486V40.005H48.3535V42Z" fill="#63AAEB"/>
<path d="M1.99631 0.0131454L22.0579 0.0131454V2.00818H24.053L24.053 19.9585H16.0778V4.00322H7.98142L7.98142 19.9585H0.00127625L0.00127625 2.00818H1.99631V0.0131454Z" fill="#63AAEB"/>
</svg>
    </div>
    
      <div
        style="
          font-weight: 500;
          font-size: 16px;
          line-height: 20px;
          color: black;
          padding-top: 40px;
          padding-bottom: 20px;
        "
      >
        Greetings,
      </div>
      <div
        style="
          font-weight: 500;
          font-size: 16px;
          color: black;
          line-height: 22px;
        "
      >
      We have recieved a request to reset your password. If you requested this change, your password reset code is:
      </div>
      <div
        style="
          font-size: 48px;
          font-weight: bold;
          color: #63AAEB;
          padding-bottom: 30px;
          padding-top: 30px;
        "
      >
        ${code}
      </div>



      <div
        style="
          font-weight: 500;
          font-size: 16px;
          color: black;
          line-height: 22px;
          padding-bottom: 10px;
          text-align: justify;
        "
      >
      Don’t recognize this activity? Please
      <a style="color: #63AAEB" href="https://www.nyyu.io/app/forgot-password/">reset your password</a>
      and contact 
      <a style="color: #63AAEB" href="https://help.nyyu.io/hc/en-gb/requests/new">customer support </a>
      immediately.
      </div>

      <div
        style="
          font-size: 10px;
          line-height: 14px;
          color: black;
          padding-top: 36px;
          padding-bottom: 10px;
          text-align: justify;

        ">
          <strong>Kindly note:</strong> Please be aware of phishing sites and always make sure you are visiting the official nyyu.io website when entering sensitive data.
          </div>

          <div
          style="
            font-size: 10px;
            line-height: 14px;
            color: black;
            padding-bottom: 10px;
            text-align: left;
          ">
          © 2022 NYYU. All rights reserved.
        </div>
      </div>
    </div>
  </body>
</html>
