<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat|Arial|Raleway"
      rel="stylesheet"
    />
    <title>NDB Money</title>
  </head>
  <body>
    <div
      style="
        width: max-content;
        height: auto;
        padding-left: 30px;
        font-family: 'Montserrat', Arial, Raleway;
        overflow: hidden;
      "
    >
      <img
        src="https://ndb-sale.s3.eu-west-1.amazonaws.com/email/ndb_logo.png"
        style="width: 82px; height: 31px; padding-top: 35px"
        alt="Logo"
      />
      <div
        style="
          font-weight: 500;
          font-size: 16px;
          line-height: 20px;
          color: black;
          padding-top: 80.5px;
          padding-bottom: 11px;
        "
      >
        Greetings,
      </div>
      <div
        style="
          font-weight: 500;
          font-size: 16px;
          line-height: 20px;
          color: black;
        "
      >
        User account is created. Please verify your account with the code:
      </div>
      <div
        style="
          font-size: 48px;
          line-height: 59px;
          font-weight: bold;
          color: #23c865;
          padding-bottom: 52px;
          padding-top: 58px;
        "
      >
        ${code}
      </div>
      <div
        style="
          font-weight: 500;
          font-size: 16px;
          line-height: 20px;
          color: black;
        "
      >
        If this wasn't you, please ignore this message.
      </div>
      <div
        style="
          font-size: 10px;
          line-height: 12px;
          color: #1e1e1e;
          opacity: 0.6;
          padding-top: 141px;
          padding-bottom: 39px;
          text-align: center;
        "
      >
        <div>© 2021 Voltamond SA. All rights reserved.</div>
        <div style="margin-top: 6px">
          <div style="margin-right: 14px; display: inline">ndb.money</div>
          <div style="margin-right: 14px; display: inline">
            info@ndb.technology
          </div>
          <div style="display: inline">+1 (650) 252 - 0002</div>
        </div>
      </div>
    </div>
  </body>
</html>
