<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Welcome to NDB</title>
</head>
<body>
	<div style="margin-top: 10px">Greetings</div>
	<br/>
	<div> User account is created. Please verify your account with the code.</div>
	<div>
		<h4>Activation Code : <span style="font-weight: bold;">${code}</span></h4>
	</div>
</body>
</html>