package com.ndb.auction.models;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;


@AllArgsConstructor
@DynamoDBTable(tableName = "Avatar_profile")
public class AvatarProfile {
	
	private String id;
	private String name;
	private String surname;
	private String shortName;
	private List<SkillSet> skillSet;
	private List<AvatarSet> avatarSet;
	private String enemy;
	private String invention;
	private String bio;
	
	public AvatarProfile() {
		
	}
	
	public AvatarProfile(
		String name,
		String surname,
		String shortName,
		List<SkillSet> skillSet,
		List<AvatarSet> avatarSet,
		String enemy,
		String invention,
		String bio
	) {
		this.name = name;
		this.surname = surname;
		this.shortName = shortName;
		this.skillSet = skillSet;
		this.avatarSet = avatarSet;
		this.enemy = enemy;
		this.invention = invention;
		this.bio = bio;
	}

	@DynamoDBHashKey(attributeName="id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute(attributeName="fname")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@DynamoDBAttribute(attributeName="surname")
	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@DynamoDBAttribute(attributeName="short_name")
	public String getShortName() {
		return shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@DynamoDBAttribute(attributeName="skill_set")
	public List<SkillSet> getSkillSet() {
		return skillSet;
	}

	public void setSkillSet(List<SkillSet> skillSet) {
		this.skillSet = skillSet;
	}

	@DynamoDBAttribute(attributeName="avatar_set")
	public List<AvatarSet> getAvatarSet() {
		return avatarSet;
	}

	public void setAvatarSet(List<AvatarSet> avatarSet) {
		this.avatarSet = avatarSet;
	}

	@DynamoDBAttribute(attributeName="enemy")
	public String getEnemy() {
		return enemy;
	}

	public void setEnemy(String enemy) {
		this.enemy = enemy;
	}

	@DynamoDBAttribute(attributeName="invention")
	public String getInvention() {
		return invention;
	}

	public void setInvention(String invention) {
		this.invention = invention;
	}

	@DynamoDBAttribute(attributeName="bio")
	public String getBio() {
		return bio;
	}

	public void setBio(String bio) {
		this.bio = bio;
	}

}
