package com.ndb.auction.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
// import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Avatar_component")
public class AvatarComponent {
	
	private String groupId;
	private String compId;
	private Integer tierLevel;
	private Double price;
	private Integer limited;
	private Integer purchased;
	// private String base64Image;

	public AvatarComponent() {
		
	}
	
	public AvatarComponent(String groupId, Integer tierLevel, Double price, Integer limited) {
		this.groupId = groupId;
		this.tierLevel = tierLevel;
		this.price = price;
		this.limited = limited;
		this.setPurchased(0);
	}
	
	@DynamoDBHashKey(attributeName="group_id")
	public String getGroupId() {
		return groupId;
	}
	
	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@DynamoDBRangeKey(attributeName="comp_id")
	@DynamoDBAutoGeneratedKey
	public String getCompId() {
		return compId;
	}

	public void setCompId(String compId) {
		this.compId = compId;
	}
	
	@DynamoDBAttribute(attributeName="tier_level")
	public Integer getTierLevel() {
		return tierLevel;
	}

	public void setTierLevel(Integer tierLevel) {
		this.tierLevel = tierLevel;
	}
	
	@DynamoDBAttribute(attributeName="price")
	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}
	
	@DynamoDBAttribute(attributeName="limited")
	public Integer getLimited() {
		return limited;
	}

	public void setLimited(Integer limited) {
		this.limited = limited;
	}
	
	@DynamoDBAttribute(attributeName="purchased")
	public Integer getPurchased() {
		return purchased;
	}

	public void setPurchased(Integer purchased) {
		this.purchased = purchased;
	}

	public void increasePurchase() {
		this.purchased++;
		this.limited--;
	}

	// @DynamoDBIgnore
	// public String getBase64Image() {
	// 	return base64Image;
	// }

	// public void setBase64Image(String base64Image) {
	// 	this.base64Image = base64Image;
	// }
	
}
