package com.ndb.auction.models;

import java.sql.Timestamp;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "LocationLog")
public class LocationLog {

	@DynamoDBHashKey(attributeName = "user_id")
	private String userId;

	@DynamoDBHashKey(attributeName = "log_id")
	@DynamoDBAutoGeneratedKey
	private String logId;

	@DynamoDBAttribute(attributeName = "ip_address")
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "ip_address")
	private String ipAddress;

	@DynamoDBAttribute(attributeName = "is_vpn")
	private boolean isVpn;

	@DynamoDBAttribute(attributeName = "is_proxy")
	private boolean isProxy;

	@DynamoDBAttribute(attributeName = "is_tor")
	private boolean isTor;

	@DynamoDBAttribute(attributeName = "is_relay")
	private boolean isRelay;

	@DynamoDBAttribute(attributeName = "city")
	// @DynamoDBIndexHashKey(globalSecondaryIndexName = "country_city")
	private String city;

	@DynamoDBAttribute(attributeName = "region")
	private String region;

	@DynamoDBAttribute(attributeName = "country")
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "country_city")
	private String country;

	@DynamoDBAttribute(attributeName = "continent")
	private String continent;

	@DynamoDBAttribute(attributeName = "region_code")
	private String regionCode;

	@DynamoDBAttribute(attributeName = "country_code")
	private String countryCode;

	@DynamoDBAttribute(attributeName = "continent_code")
	private String continentCode;

	@DynamoDBAttribute(attributeName = "latitude")
	private float latitude;

	@DynamoDBAttribute(attributeName = "longitude")
	private float longitude;

	@DynamoDBAttribute(attributeName = "vpnapi_response")
	private String vpnapiResponse;

	@DynamoDBAttribute(attributeName = "final_result")
	private String finalResult;

	@DynamoDBTypeConvertedTimestamp
	private Timestamp regTime;

}
