package com.ndb.auction.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Notification")
public class Notification {
	
	private String id;
	private String userId;
	private long t;
	private String msg;
	private boolean read;
	
	@DynamoDBIndexRangeKey(attributeName="id")
    @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	@DynamoDBHashKey(attributeName="user_id")
	public String getUserId() {
		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}
	
	@DynamoDBAttribute(attributeName="t")
	public long getStamp() {
		return t;
	}
	public void setStamp(long stamp) {
		this.t = stamp;
	}
	
	@DynamoDBAttribute(attributeName="msg")
	public String getMessage() {
		return msg;
	}
	public void setMessage(String message) {
		this.msg = message;
	}
	
	@DynamoDBAttribute(attributeName="read")
	public boolean isRead() {
		return read;
	}
	public void setRead(boolean read) {
		this.read = read;
	}		
}
