package com.ndb.auction.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@DynamoDBTable(tableName = "Notification2")
public class Notification2 {

    public Notification2(String userId, int type, String title, String msg) {
        this.userId = userId;
        this.nType = type;
        this.read = false;
        this.title = title;
        this.msg = msg;
    }

    @DynamoDBHashKey(attributeName = "user_id")
    private String userId;

    @DynamoDBRangeKey(attributeName = "time_stamp")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Long timeStamp;

    @DynamoDBAttribute(attributeName = "n_type")
    private int nType;

    @DynamoDBAttribute(attributeName = "n_read")
    private boolean read;

    @DynamoDBAttribute(attributeName = "n_title")
    private String title;

    @DynamoDBAttribute(attributeName = "n_msg")
    private String msg;
}
