package com.ndb.auction.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Notification")
public class Notification {

	// Notification ID : this is unique for same broadcasting
	private String id; // RangeKey
	private String userId; // SortKey
	
	private String title; 
	private String msg; 

	private long t; // TimeStamp
	private boolean read; // Unread/Read Flag
	
	private Integer type; // Type : ex] Round Start, End, ...
	private boolean broadcast; // Broadcasting or Private notification.

	public Notification() {
		this.read = false;
		this.broadcast = true;
	}

	 /**
	 * create new payment and check confirm status
	 * @param type : Notification Type, ex] ROUND_START, ROUND_END, WIN, LOSE, BID,...
	 * @param title : Notification Title
	 * @param msg : Notification Content
	 * @return void
	 */
	public Notification(Integer type, String title, String msg) {
		this.title = title;
		this.msg = msg;

		this.read = false;
		this.type = type;
		this.broadcast = false;
	}

	public Notification(Notification n) {
		this.id = n.id; 
		this.userId = n.userId; 
		this.title = n.title; 
		this.msg = n.msg; 
		this.t = n.t;
		this.read = n.read; 
		this.type = n.type;
		this.broadcast = n.broadcast; 
	}

	@DynamoDBRangeKey(attributeName = "id")
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBHashKey(attributeName = "user_id")
	public String getUserId() {
		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}

	@DynamoDBAttribute(attributeName = "t")
	@DynamoDBAutoGeneratedTimestamp
	public long getStamp() {
		return t;
	}
	public void setStamp(long stamp) {
		this.t = stamp;
	}

	@DynamoDBAttribute(attributeName = "title")
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}

	@DynamoDBAttribute(attributeName = "msg")
	public String getMessage() {
		return msg;
	}
	public void setMessage(String message) {
		this.msg = message;
	}

	@DynamoDBAttribute(attributeName = "read_flag")
	public boolean isRead() {
		return read;
	}
	public void setRead(boolean read) {
		this.read = read;
	}

	@DynamoDBAttribute(attributeName = "type")
	public Integer getType() {
		return type;
	}
	public void setType(Integer type) {
		this.type = type;
	}

	@DynamoDBAttribute(attributeName = "broadcast")
	public boolean isBroadcast() {
		return broadcast;
	}
	public void setBroadcast(boolean broadcast) {
		this.broadcast = broadcast;
	}
}
